# Generated by Django 5.0.1 on 2024-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0003_alter_class_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='classBooked',
            field=models.CharField(choices=[('YOGA', 'YOGA'), ('SPIN', 'SPINNING'), ('FFT', 'FUNCTIONAL FITNESS TRAINING')], max_length=4),
        ),
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.CharField(default='10 AM', max_length=2),
        ),
    ]
