# Generated by Django 5.0.1 on 2024-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0004_remove_class_user_class_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.CharField(choices=[('10', '10 AM'), ('11', '11 AM'), ('12', '12 PM'), ('13', '1 PM'), ('14', '2 PM'), ('15', '3 PM'), ('16', '4 PM')], max_length=2),
        ),
    ]
